fitbenchmarking/example_runScripts.py, fitbenchmarking/fitting_benchmarking.py, fitbenchmarking/input_parsing.py
This is the first PR
Problem with importing the file is fixed if os.sep is used instead of "\\" at https://github.com/mantidproject/fitbenchmarking/blob/29eaecbf601dd392dc82d2d8844f871ebb5ba78e/fitbenchmarking/input_parsing.py#L226
To test:
1. Make sure that run_data = "neutron" in example_runScript.py
2. Run example_runScript in the mantidpython console
3. Check if the right neutron files are imported (i.e. compare console output with the files in the fitbenchmarking/benchmark_problems/Neutron_data)
=> Using os.sep instead of "\\"

fitbenchmarking/example_runScripts.py, fitbenchmarking/post_processing.py, fitbenchmarking/results_output.py, fitbenchmarking/test_result.py, setup.py
This comes after PR #21 
This fixes #16
Just included install_packages=["python-docutils"] in setup.py. When users will run setup, docutils will also be installed on their machine.
To test:
1. On Ubuntu 16 make sure the package docutils is not installed
- check /usr/lib/python2.7, if you find any folder with docutils in its name run `sudo apt remove python-docutils` in the terminal
- check /usr/local/lib/python2.7, if you find any folder with docutils in its name run `sudo rm -r /usr/local/lib/python2.7/NameOfFolderWithDocutils`
2. Run example_runScript.py in mantidpython
- to do this open a terminal and run `cd /opt/Mantid/bin` or wherever mantidplot is installed on your machine
- once in the bin directory, run `./mantidpython` in terminal
- here cd to the fitbenchmarking folder and run …
=> Docutils dependency now included in setup.py

fitbenchmarking/fitting_benchmarking.py, fitbenchmarking/input_parsing.py
This comes after #20 
This fixes #18
Deleted unused code and replaced ignored lines terminal output with just the number of ignored lines.
To test:
1. Make sure run_data is "nist" in example_runScripts.py.
2. Run example_runScripts.py from the mantidpython console.
3. Pause the program after loading file, the file that is being loaded and the number of ignored lines should be displayed in the terminal window.
4. Go to fitbenchmarking\benchmark_problems\NIST_nonlinear_regression and check if the number of ignored lines in the corresponding file matches the displayed number ignored lines.
Note: to see which lines were ignored explicitly uncomment https://github.com/mantidproject/fitbenchmarking/blob/08b331a23f483ba4ce55c72ccac7ffb503771bdd/fitbenchmarking/input_parsing.py#L138
=> Stopped outputting NIST ignored files

fitbenchmarking/example_runScripts.py, fitbenchmarking/fitting_benchmarking.py, fitbenchmarking/post_processing.py, fitbenchmarking/results_output.py
This comes after #18 
The ValueError that is raised by the Simplex minimizer in problem WISH17701 panel 103 tube 3 calibration, peak 9 1 is now caught and a nan value is outputted in the table.
To test:
1. In example_runScript.py make sure
- minimizers contains 'Simplex'
- run_data = 'neutron'
2. Run example_runScript.py in the mantidpython terminal
3. Check the table comparison_weighted_v3.8_acc_nist_lower.html under column Simplex, last row, should display nan
Notes: 
- The table name is wrong, this is a known issue, changing it to neutron causes a crash #22 .
- This only catches RuntimeErrors and ValueErrors, if the fit algorithm returns any other kind of error, the problem is still there. Doing an except that catches everything is generally bad practice so I refrained from doing so …
=> Output nan in the table when fitting fails

fitbenchmarking/input_parsing.py
Fixed https://github.com/mantidproject/fitbenchmarking/blob/ee3307bd8f3e9210074b55765b44f45dab591f42/fitbenchmarking/input_parsing.py#L249
This line was causing an error: `global name 'k' is not defined`
Change k to sep_idx
=> Fixed issue with master when parsing neutron data

fitbenchmarking/input_parsing.py
Fixes #37
1. Make sure that in example_runScripts.py `run_data` is set to "nist".
2. Run example_runScripts.py in the mantidpython console.
3. Compare the results with the output you get from following the same steps in master branch.
=> Code now considers only one column when parsing nist file

fitbenchmarking/fitting_benchmarking.py
Fixes #50
Faking observational errors now takes the square root of the absolute value of y data.
1. In `example_runScript.py` make sure that `run_data = "nist"`.
2. In the mantidpython console, run `example_runScript.py`.
3. Check the acc_high_difficulty nist table that is produced, the Bennett5 rows should now contain numbers instead of `nans`.
=> Fake observational errors now can deal with negative values

fitbenchmarking/example_runScripts.py, fitbenchmarking/results_output.py
Fixes #22
Inside build_visual_display_page, a workspace was repeatedly created which apparently produces a crash. The workspace was not used anywhere so simply deleting that line solved the issue.
1. In `example_runScript.py` make sure that `run_data = "neutron"`.
2. Run `example_runScript.py` in the mantidpython console.
3. It should run smoothly now. Additionally, tables are created which link to the visual display pages.
**Note:** Visual display pages are broken. This is a known issue #
=> Fixed build_visual_display_page producing a crash

fitbenchmarking/example_runScripts.py, fitbenchmarking/fitting_benchmarking.py, fitbenchmarking/input_parsing.py
Fixes #55
Changed `example_runScript` such that it now runs all tests at once.
1. Run `example_runScript.py` in the mantidpython console.
2. Check if all the output is in the results folder.
**Note:** This was giving an error after completing execution: `RuntimeError maximum recursion depth reached` so I increased the recursion depth here:
https://github.com/mantidproject/fitbenchmarking/blob/acf175d8f33b932b73a653eef98ce6d0d6cb341a/fitbenchmarking/example_runScripts.py#L5-L6
I have not found any other way that fixes the problem.
=> Run all tests at once added

example_scripts/README.md, example_scripts/example_runScripts.py
Fixes #61 
Moved `example_runScripts.py` outside the fitbenchmarking directory.
1. Run `example_runScripts.py` in the matnidpython console.
2. Check if all the neutron and nist results appear in the designated results folder.
=> Created example run scripts folder

example_scripts/example_runScripts.py, fitbenchmarking/example_runScripts.py, fitbenchmarking/fitting_benchmarking.py, fitbenchmarking/results_output.py
Fixes #69 
Visual display pages now reside in `/fitbenchmarking/fitbenchmarking/results/neutron/VDPages/` and the tables link to them correctly.
1. Run `example_runScripts.py` in the mantidpython console.
2. Check if the links in the tables available at `/fitbenchmarking/fitbenchmarking/results/neutron/Tables/` point to the correct VDpages
**Note:** VDpages are still broken for the time. They will be fixed in #64 .
=> Created visual display page folder in new dir structure

fitbenchmarking/example_runScripts.py, fitbenchmarking/fitting_benchmarking.py, fitbenchmarking/results_output.py
Fixes #64
Visual display pages now work and display some basic figures.
1. Run `example_runScripts.py` in mantidpython.
2. Go to the neutron tables, open them and then click on the links.
- neutron tables are located at "/fitbenchmarking/fitbenchmarking/results/neutron/Tables"
=> Fixed visual display pages

example_scripts/example_runScripts.py
Here
* removal of not used group_names in this example script
* comment on NIST oddity
* more clear code comment for labels
1. run the changed example_runScripts.py script and check it completes without errors
2. check changes OK
=> Improve reference to group names in example script and NIST oddity

benchmark_problems/README.md, example_scripts/example_runScripts.py, fitbenchmarking/parsing/parse_fitbenchmark_data.py
Reimplement the function `get_data_file` in `parse_fitbenchmark_data.py` to use os.walk to find the right directory for the data files.
Also update README in benchmark_problems accordingly
Fixes #158 
1. Run `example_runScripts.py` with problems type FitBenchmark
2. Try renaming the folder containing FitBenchmarking data files (currently named data_files) which is under the folders benchmark_problems/Muon_data and benchmark_problems/Neutron_data
=> Remove all references to "data_files" string in code

fitbenchmarking/fitting/mantid/tests/test_func_def.py, fitbenchmarking/fitting/mantid/tests/test_main.py, fitbenchmarking/fitting/mantid/tests/test_prepare_data.py, fitbenchmarking/fitting/scipy/tests/test_fitbenchmark_def.py, fitbenchmarking/fitting/scipy/tests/test_nist_def.py, fitbenchmarking/fitting/scipy/tests/test_prepare_data.py, fitbenchmarking/fitting/tests/test_misc.py, fitbenchmarking/parsing/base_fitting_problem.py, fitbenchmarking/parsing/tests/test_parse_fitbenchmark_data.py, fitbenchmarking/parsing/tests/test_parse_nist_data.py
Any instantiation of BaseFittingProblem has been removed and replaced by its sub-class.
Also. further attempts to instantiate BaseFittingProblem would be prevented along with an error message.
Fixes #185 
1. Try to instantiate BaseFittingProblem and observe the error message on console
=> Prevent any instantiation of BaseFittingProblem

docs/source/users/options.rst, example_scripts/example_runScripts_expert.py, fitbenchmarking/fitbenchmark_one_problem.py, fitbenchmarking/fitbenchmarking_default_options.json, fitbenchmarking/fitting_benchmarking.py
Fixes #257 
Allows FitBenchmarking to calls a minimizer multiple of times and thus calculates an average elapsed time using `timeit`.
1. Check the accuracy tables are still the same 
2. New timing results are consistent between runs
=> 257 Adding averaging time using timeit

docs/source/users/index.rst, docs/source/users/notes.rst, docs/source/users/options.rst
Fixes #295 
Adds table of known combinations which may cause erroneous results:
[notes](https://fitbenchmarking.readthedocs.io/en/295-notable_combinations_table/users/notes.html)
1. Verify that the new table covers known issues
=> 295 notable combinations table

.travis.yml
Fixes #299 
Adds an email notification.
Sets the systests to optional while they are outdated.
1. Read though the yaml and the docs [here](https://docs.travis-ci.com/user/notifications#configuring-email-notifications) to verify the notifications. (Unfortunately I don't think this can be tested properly until it has been merged for a day.)
2. Follow up 1 day after merging by checking for an email (if master is failing)
=> 299 travis notifications

fitbenchmarking/fitting/misc.py, fitbenchmarking/fitting/tests/test_misc.py
Fixes #319 
Corrects the wrongly reported `chi_sq` value.
1. Check `chi_sq` correctly implement.
=> Correcting chi_sq

fitbenchmarking/fitbenchmark_one_problem.py
Fixes #336 
Changes the order of execution so that for each initial value the fitbenchmarking runs through the each software, such that the output to the screen is:
1. Check that the html pages are consistent. 
=> Reordering execution runtime

fitbenchmarking/fitting/controllers/controller_factory.py, fitbenchmarking/parsing/parser_factory.py
Fixes #321
Checks if file exists, and if file does exist, this assumes a dependency is missing.
Otherwise it prints the old message.
1. Break one of the controllers in a way that will report an ImportError (e.g. try `import fitbenchmarking.fake_pkg`) and check the error message.
2. Try to run a controller that does not exist and check the error message
=> Improve error messages for failed factory imports

requirements.txt
Fixes #350 
Pins version of coverage which seems to be the only difference between the last pass and fail
=> Issue #350: Fixes coveralls issue

fitbenchmarking/cli/main.py, fitbenchmarking/results_processing/plots.py, fitbenchmarking/results_processing/visual_pages.py
Fixes #399 
Makes results_index.html use relative links so they work on windows and Linux.
Removes "file:///" from the plots as this is not needed for relative links.
1. Run FitBM and check that links work on windows
=> Issue #399: Make remaining absolute links relative and remove "file:///"

fitbenchmarking/cli/main.py, fitbenchmarking/cli/tests/test_main.py, fitbenchmarking/systests/test_regression.py
Fixes #374 
Checks to see if input options file exists and that it has the right extension.
1. Check a `RuntimeError` is raised when given a wrong `ini` file location.
1. Check a `RuntimeError` is raised when the given file doesn't have an `ini` extension. 
=> Missing ini file

fitbenchmarking/core/fitbenchmark_one_problem.py, fitbenchmarking/core/fitting_benchmarking.py, fitbenchmarking/utils/output_grabber.py, fitbenchmarking/utils/tests/test_output_grabber.py
Fixes #168 
Adds a output grabber based on [this.](https://stackoverflow.com/questions/24277488/in-python-how-to-capture-the-stdout-from-a-c-shared-library-to-a-variable?rq=1)
1. Check that the third party output is removed.
=> Remove extra third party output

azure-pipelines.yml
Created first Windows CI setup with Azure pipelines.
CI here builds FitBenchmarking and run one of its tests.
More widely as reported elsewhere Windows support of FitBenchmarking been broken. This is first step to get CI support setup for Windows to avoid Windows support is broken sometime later again.
Fixes #171
##Test
* Check builds pass
* Check that has permission (other than me) to access Azure build
=> First attempt set up Windows CI with Azure Pipelines

fitbenchmarking/controllers/base_controller.py, fitbenchmarking/controllers/tests/test_controllers.py, fitbenchmarking/core/fitting_benchmarking.py
Fixes #588 
Adds `final_params` to the base controller function `check_attributes` to check whether the elements in the numpy ndarray of  `final_params` are not `nan` or `inf`.
1. Check that the exception is not raised, the easiest way to do this is to run `scipy` software with all default minimizers and `SLSQP`.
=> Update check_attributes function in base controller

docs/source/users/running.rst, fitbenchmarking/core/fitting_benchmarking.py, fitbenchmarking/core/tests/test_fitting_benchmarking_benchmark.py, fitbenchmarking/core/tests/test_fitting_benchmarking_benchmark_problems.py, fitbenchmarking/parsing/nist_parser.py
Fixes #589 
Updates the first example in the docs to be from the NIST problem set. Also, allows problem sets with different problem types (`mantid`, `NIST`, etc) to be run without errors if an external package is not installed. 
1. Check new first example runs without any warnings for default installation.
2. Check `simple_tests` run with just a warning for the mantid problems
3. Check a Mantid data set (`Neutron` or `Muon`) raise a `FitBenchmarking ran with no results` error.
=> Updating first example docs

fitbenchmarking/core/fitting_benchmarking.py
Fixes #616 
Adds checks that the computed values for `chi_sq` and `runtime` are not NaN. 
1. Check default options with SIF and NIST problem sets
=> Fixing chi_sq and runtime NaN issue

conftest.py, docs/source/users/index.rst, docs/source/users/tests.rst, fitbenchmarking/controllers/tests/test_controllers.py, fitbenchmarking/parsing/tests/test_parsers.py, fitbenchmarking/systests/test_regression.py
Fixes #648 
Adds documentation for FitBenchmarking tests and splits the tests into two options `all` and `default` tests.
1. Check the docs make are clear
2. Check the tests pass
=> Adds tests docs

fitbenchmarking/systests/test_regression.py, fitbenchmarking/utils/options.py, fitbenchmarking/utils/tests/test_options_fitting.py
Fixes #656 
Fixes #607
Sets the default minimizers to be `scipy` and `scipy_ls`.
1. Check tests pass 
2. Check that if you `pip` install FitBenchmarking without any external packages (`pip` installable or otherwise) you can run FitBenchmarking.
=> Updating default minimizers in options

Docker/BasicInstall/Dockerfile
Azure pipelines adds a new user with sudo permissions to run tests in a container.
This means that the user has no root access on standard machines as these do not include sudo (?!).
Add sudo here so that pipelines can install python packages to the venv that we create with the root (default) account.
Install sudo in dockerfile
Fixes #693
1. Build a docker container from the dockerfile:
`docker build --tag test Docker/BasicInstall`
2. Log in to the container
`docker run -it test /bin/bash`
3. Verify sudo is installed
`which sudo`
--- OR ---
3. Add a new user
`useradd -m -u 1001 vsts_azpcontainer`
4. Give new user sudo priveledges
`groupadd azure_pipelines_sudo`
`usermod -a -G azure_pipelines_sudo vsts_azpcontainer`
`su -c "echo '%azure_pipelines_sudo ALL=(ALL:ALL) NOPASSWD:ALL' >> …
=> Issue 693: Add sudo to dockerfile

fitbenchmarking/results_processing/plots.py
Revrts to using the minimizer arg for generating plots rather than the stored argument.
Fixes #708
1. Run Fitbenchmarking with plots
2. Check that plots display the correct minimizer
3. Check that plots folder contains a full set of files
=> Issue #708: Use min arg rather than best

.github/workflows/release.yml
I just found theres a release trigger which seems better than building on every push to release-**
=> Change action trigger to only run if a release is published

.github/workflows/main.yml, .github/workflows/release.yml, README.md
Touches up badges before submitting build to pypi, so that versions are fixed.
I'm not sure we'll be able to do the same for the badges that show up on the docs though as RTD pulls the tagged commit so I can't intercept it before it goes.
=> Fix badges in branch

Docker/BasicInstall/Dockerfile
Latest minuit requires cmake version 3.13, this is not available from the package manager on Ubuntu 18.04 so switch to 20.04.
=> Upgrade docker version

Docker/FullInstall/Dockerfile
Update docker container to build mantid.
Builds it into /opt/Mantid (standard location).
Note, can't clean the source files away as they're used for the python API
=> Build mantid

docs/source/users/problem_definition_files/native.rst, fitbenchmarking/controllers/dfo_controller.py, fitbenchmarking/controllers/minuit_controller.py, fitbenchmarking/controllers/ralfit_controller.py, fitbenchmarking/controllers/tests/test_controllers.py, fitbenchmarking/systests/linux_expected_results/all_parsers.txt
Fixes [#740](https://github.com/fitbenchmarking/fitbenchmarking/issues/740)
Add upper and lower bounds to each controller and add tests to check bounds are respected. 
In the dfo controller, the argument `rhobeg` is also checked. This is because when specifying bounds, the gap between a lower and upper bound must be at least `2*rhobeg` -if this condition is not satisfied then the value of `rhobeg` is changed to the maximum possible value given the bounds for the problem.
1. Run Fitbenchmarking with minuit, ralfit and dfo fitting software
2. For problems with no parameter bounds, check that results are consistent
3. For SASView problems, check that bounds are respected
Style: …
=> Add support for bounds for minuit, ralfit and dfo

docs/source/contributors/workflow.rst, docs/source/users/install_instructions/fitbenchmarking.rst, docs/source/users/options/plotting_option.rst, docs/source/users/running.rst, fitbenchmarking/controllers/minuit_controller.py
**Users -> Installation -> Installing FitBenchmarking and default fitting packages:** users/install_instructions/fitbenchmarking.rst edited so that last bullet point list on page now formatted in line with other bullet points.
**Contributors -> Module Index -> fitbenchmarking.controllers.minuit_controllermodule:** minuit_controller.py docstring updated to correct  "pacakage" to "package".
**Users -> Running FitBenchmarking:** users/running.rst "A example problems can be downloaded" corrected to "Example problems can be downloaded"...
**Contributors -> Git Workflow:**  contributors/workflow.rst edited so that on the first mention of "pull request" the acronym PR is introduced like so "pull request (PR)" and any subsequent references to pull requests now use the acronym.
**Users -> …
=> Updated documentation .rst files and the minuit_controller.py docstring to address written expression errors

fitbenchmarking/parsing/fitting_problem.py, fitbenchmarking/parsing/tests/test_fitting_problem.py, fitbenchmarking/utils/exceptions.py
Fixes #777 
1. Run problems with incorrect parameter names in `parameter_ranges` to check warning message appears as expected
2. Check that problems will correct `parameter_ranges` still run as expected
=> Add warning message for incorrect parameter names in parameter_ranges

fitbenchmarking/core/fitting_benchmarking.py, fitbenchmarking/core/results_output.py, fitbenchmarking/core/tests/test_fitting_benchmarking_benchmark.py, fitbenchmarking/core/tests/test_fitting_benchmarking_benchmark_problems.py, fitbenchmarking/core/tests/test_fitting_benchmarking_jacobians.py, fitbenchmarking/core/tests/test_fitting_benchmarking_minimizers.py, fitbenchmarking/core/tests/test_fitting_benchmarking_software.py, paper/paper.bib
Remove linting errors within the core directory.
The only linting messages remaining are refactor suggestions - too-many-nested-blocks and duplicate-code
The duplicate code looks to be boiler plate code in the tests
Fixes #767
1. Run pylint and flake8 on the core directory
2. Check the changes made
=> Issue #767: Fix linting complaints

fitbenchmarking/parsing/nist_data_functions.py
Fixes #601
1. Run is_safe for "np.pi*x"
=> Check pi as a value not a function for nist parser - is_safe method

fitbenchmarking/templates/table_template.html
"FitBenmarking" replaced with "FitBenchmarking" see #845.
=> Failed minimizers report - corrected typo

fitbenchmarking/utils/options.py
Fixes #868 
1. Check that the matlab stats fitting software can now be run when selected in an options file
=> Add matlab_stats back to valid fitting

fitbenchmarking/templates/table_style.css
Reintroduce the `overflow: hidden;` line in the CSS which looks to have been removed accidentally during a previous change.
Fixes #875
1. Do the links work?
2. Does table scrolling still work?
=> Add overflow hide back in

docs/source/users/options/minimizer_option.rst
Fixes #864 
1. Check that the minimizer links in the results table now point to the correct fitting software from the Minimizer Options docs page
=> Fix incorrect minimizer links

docs/source/contributors/install_instructions.rst, docs/source/users/install_instructions/externals.rst, docs/source/users/options/plotting_option.rst
This PR adds a note to the contributor installation instructions mentioning that the editable `-e` flag should be used when installing from source as a contributor.
I also fixed a few minor typos I noticed when reading through the docs.
Fixes #916 
Read the documentation changes and make sure they make sense
=> Contributor Editable Installation Note

fitbenchmarking/results_processing/base_table.py, fitbenchmarking/results_processing/local_min_table.py, fitbenchmarking/results_processing/tests/test_base_table.py
This PR fixes a bug where the colourbars that are saved were not being returned and so were said to be 'None' in the comparison page. It also ensures that the path to the colourbars is a relative path so the bug in the issue doesn't occur when ssh tunnelling to a different machine.
Fixes #911
1. Run a fitbenchmark of any problem. Open the results and you should see the colourbar is present instead of saying 'None'
2. Right click the colour bar and Inspect it. The path to the image should be relative.
=> Use Relative Path for colourbar image

fitbenchmarking/templates/table_descriptions.rst
This PR adds the time units of the runtime to the documentation generated after doing a fit benchmark.
Fixes #897
1. Read the changes to the documentation and make sure they make sense.
=> Add time units to runtime table description

.github/workflows/main.yml
This PR makes sure fitbenchmarking is pip installed before the surplus requirements. It is better to do it this way around so that the order of installs mirrors the setup instructions in the fitbenchmarking documentation.
Fixes #894 
1. Make sure the tests pass ok
=> Install Surplus Requirements after Fitbenchmarking install in github actions

docs/source/users/options/minimizer_option.rst, docs/source/users/problem_definition_files/native.rst, fitbenchmarking/results_processing/base_table.py, fitbenchmarking/results_processing/tests/expected_results/acc.html, fitbenchmarking/results_processing/tests/expected_results/compare.html, fitbenchmarking/results_processing/tests/expected_results/local_min.html, fitbenchmarking/results_processing/tests/expected_results/runtime.html
This PR makes it so that we can have long-form names for the minimizers in the documentation without breaking the links between the results tables and these minimizers. There is more information on the implementation in the issue.
I also fixed a warning about a missing file when building the docs. I've left the fix in this PR as it was simple
Fixes #881
1. Checkout this branch
2. Build the docs `.\docs\make.bat html` (make sure you have sphinx and m2r2 pip installed)
2. Browse to and open the `docs\build\html\users\options\minimizer_option.html` file
3. Try linking to each minimizer software by putting `#<minimizer-name>` on the end of the opened html link. For software with a space in the name like scripy ls, use a dash in place of the space like `#scipy-ls`
4. They should each link to …
=> Better Minimizer Link Handling

docs/source/users/options/minimizer_option.rst, fitbenchmarking/core/fitting_benchmarking.py, fitbenchmarking/core/tests/test_fitting_benchmarking_software.py, fitbenchmarking/results_processing/base_table.py, fitbenchmarking/results_processing/performance_profiler.py
This PR fixes a problem where the wrong flag was being set for a MaxRuntimeError when using certain software packages (such as mantid) when benchmarking.
This PR also makes it so that nan and inf results are now shown in the comparison table even when it is nan and inf for all minimizers trying to solve a given problem. I think this is a good idea because I found it confusing why certain results were not appearing as expected without a clear cause or warning.
Fixes #927
1. I fitted the SASView simple shape problems using the following options file
```
[FITTING]
software: mantid
num_runs: 1
max_runtime: 5
[MINIMIZERS]
bumps: lm-bumps
mp
scipy_ls: lm-scipy
mantid: BFGS
Levenberg-Marquardt
[PLOTTING]
make_plots: yes
[LOGGING]
external_output: log_only
```
2. The flag next to the two infs …
=> Fix MaxRuntimeError wrong flag set

.github/workflows/main.yml, ci/unit_tests.sh, ci/unit_tests_default.sh
This PR ensures the unit tests are run in one `pytest` call. This should hopefully make it easier to read the test output because there will only be one list of test failures rather than a number of different lists that you need to search for.
Fixes #955
1. Check that the unit tests still run and that there is only one `pytest` call
=> Run Unit tests in one call

.pylintrc, ci/linting_tests.sh, fitbenchmarking/cli/main.py, fitbenchmarking/cli/tests/test_main.py, fitbenchmarking/controllers/gsl_controller.py, fitbenchmarking/controllers/scipy_go_controller.py, fitbenchmarking/controllers/tests/test_controllers.py, fitbenchmarking/core/fitting_benchmarking.py, fitbenchmarking/core/tests/test_results_output.py, fitbenchmarking/jacobian/analytic_jacobian.py, fitbenchmarking/jacobian/default_jacobian.py, fitbenchmarking/jacobian/scipy_jacobian.py, fitbenchmarking/parsing/fitbenchmark_parser.py, fitbenchmarking/parsing/fitting_problem.py, fitbenchmarking/parsing/ivp_parser.py, fitbenchmarking/parsing/mantid_parser.py, fitbenchmarking/parsing/nist_parser.py, fitbenchmarking/parsing/sasview_parser.py, fitbenchmarking/results_processing/base_table.py, fitbenchmarking/results_processing/local_min_table.py, fitbenchmarking/results_processing/performance_profiler.py, fitbenchmarking/results_processing/tables.py, fitbenchmarking/results_processing/tests/test_base_table.py, fitbenchmarking/results_processing/tests/test_problem_summary_page.py, fitbenchmarking/systests/test_regression.py, fitbenchmarking/utils/tests/test_misc.py, fitbenchmarking/utils/tests/test_options_generic.py, fitbenchmarking/utils/tests/test_options_minimizers.py
This PR is an attempt to squash all refactor and convention warnings seen in the pylint output. The motivation for doing this is so that it is easier to read the failures that relate to your PR. It also ensures unwanted refactor or convention practises do not get into the code base.
Fixes #957
1. Ensure the pylint job passes. Read the output of the pylint and make sure there are no convention or refactor warnings.
=> Pylint - Fail on refactor and convention warnings

fitbenchmarking/core/fitting_benchmarking.py, fitbenchmarking/core/tests/test_fitting_benchmarking_hessians.py, fitbenchmarking/core/tests/test_fitting_benchmarking_jacobians.py, fitbenchmarking/core/tests/test_fitting_benchmarking_minimizers.py, fitbenchmarking/systests/linux_expected_results/multifit.txt, fitbenchmarking/systests/test_regression.py
This PR fixes an issue where the results for a Mantid MultiFit would not be created when the multi fit is done using a number of different jacobians or hessians. There used to be an exceptions saying the program was exiting due to unknown exception, but now it opens the browser and displays the results as expected.
Fixes #920
1. Use the options file below to run the following command 
`fitbenchmarking -p examples/benchmark_problems/MultiFit/ -o examples/test_multi_fit.ini`
```
[FITTING]
software: mantid
num_runs: 1
max_runtime: 600
[MINIMIZERS]
mantid: Levenberg-Marquardt
[JACOBIAN]
scipy: 2-point
3-point
[PLOTTING]
make_plots: yes
[OUTPUT]
results_dir: new_results/
[LOGGING]
external_output: log_only
```
2. You should get something like this
Function: Does the change do what it's …
=> Fix Mantid MultiFit results when using more than one Jacobian/Hessian

docs/source/users/problem_definition_files/native.rst, examples/benchmark_problems/simple_tests/cubic-fb.txt, examples/benchmark_problems/simple_tests/cubic-fba.txt, examples/benchmark_problems/simple_tests/gauss_exact-fb.txt, examples/benchmark_problems/simple_tests/gauss_exact-fba.txt, examples/benchmark_problems/simple_tests/gauss_noisy-fb.txt, examples/benchmark_problems/simple_tests/gauss_noisy-fba.txt, examples/benchmark_problems/simple_tests/trig_exact-fb.txt, examples/benchmark_problems/simple_tests/trig_exact-fba.txt, examples/benchmark_problems/simple_tests/trig_noisy-fb.txt, examples/benchmark_problems/simple_tests/trig_noisy-fba.txt, fitbenchmarking/mock_problems/all_parsers_set/trig_noisy-fba.txt, fitbenchmarking/mock_problems/cubic-fba-test-bounds.txt, fitbenchmarking/mock_problems/cubic-fba-test-go.txt, fitbenchmarking/parsing/fitbenchmark_parser.py, fitbenchmarking/parsing/nist_parser.py, fitbenchmarking/results_processing/fitting_report.py, fitbenchmarking/templates/fitting_report_template.html
This PR makes sure the problem descriptions are loaded for NIST, Mantid, SASView and IVP problem files. There doesn't seem to be a description option for `CUTEst` format in here so its been left out:
https://github.com/jfowkes/pycutest/blob/15794b214756f0cd54cde9e453304abc2eb8d42b/pycutest/problem_class.py#L41
I have also made the sections in the Fitting reports collapsible just like they are in the problem summary pages.
Fixes #948 
1. Run a benchmark of a mantid, NIST, SASView and IVP problem. Look at a comparison table and click the problem name - there should be a description at the top of the page that is open.
2. There should be no change to CUTEst
3. Check that the Fitting Reports have a problem description and that each section is collapsible
Function: Does the change do what it's …
=> Load problem descriptions for `NIST`, `Mantid`, `SASView` and `IVP` 

.github/workflows/release.yml, docs/source/users/install_instructions/fitbenchmarking.rst
Updates the minimum python version in the docs to be 3.7.1. It also updates the release workflow to use python 3.8 (the same python version as used in main.yml and the first major version above 3.7.1).
Fixes #986
1. Check that installation works with python 3.7.1
=> Update Minimum Python Version

docs/requirements.txt
This PR fixes a docs failure described in this issue https://github.com/CrossNox/m2r2/issues/40 by pinning mistune to 0.8.4.
Check that the docs pass, and that pinning mistune is sensible.
=> Pin mistune to `0.8.4`

fitbenchmarking/results_processing/base_table.py, fitbenchmarking/results_processing/tests/expected_results/acc.html, fitbenchmarking/results_processing/tests/expected_results/compare.html, fitbenchmarking/results_processing/tests/expected_results/local_min.html, fitbenchmarking/results_processing/tests/expected_results/runtime.html, fitbenchmarking/templates/js/table.js
This PR adds links to the generated tables when clicking on the cost function or minimizer names.
Fixes #999
1. Do a benchmark and click on the name of a cost function or minimizer in one of the generated table. Make sure they link to the appropriate documentation page
=> Add links from the tables to the cost function docs

docs/requirements.txt, docs/source/users/options/logging_option.rst
This PR fixes two issues. The first is to do with the bullet points missing in the documentation, and is fixed making sure `sphinx-rtd-theme==1.0.0` gets installed. The second issue was caused by some unintended indentation.
Credit to @AndrewLister-STFC for finding the problem with the first issue.
Fixes #1005 #1006
1. Build the docs and make sure the two attached issues are now fixed.
=> Fix bullet points not appearing in documentation

docs/source/users/BenchmarkProblems.rst
Fixes #1007 by swapping the HTTP:// calls for https:// calls
1. Check that the downloads of problem files work in edge
2.
3.
=> Fix edge downloads

fitbenchmarking/controllers/bumps_controller.py
Adds an abort test for bumps to handle max runtime aborts.
Fixes #1025 
1. @tyronerees Can you re-run the problematic ini and dataset on this branch? I tested it with bumps/SAS Complex 1D
=> Add abort test for max runtime

fitbenchmarking/controllers/base_controller.py
Fixes issue where https://fitbenchmarking.readthedocs.io/en/latest/extending/controllers.html was not displaying the flags properly.
1. Does te docs page now explain the flags in part 2.?
=> Remove unneeded noqa

fitbenchmarking/controllers/horace_controller.py, fitbenchmarking/controllers/matlab_controller.py, fitbenchmarking/controllers/matlab_curve_controller.py, fitbenchmarking/controllers/matlab_curve_controller/eval_r.m, fitbenchmarking/controllers/matlab_mixin.py, fitbenchmarking/controllers/matlab_opt_controller.py, fitbenchmarking/controllers/matlab_stats_controller.py, fitbenchmarking/controllers/tests/test_controllers.py
Fixes matlab curve fitting toolbox with max runtime
Replaces the wrapper with one written in matlab. This is written to a temp file and saved for matlab to open. The cost function and default data are passed via global variables... which might be unwise but I thought it was ok in this very bizare situation.
A side effect of this chang is that the serialisation of all matlab controllers will now be done for the cost function. With individual methods on the cost function being accessed from the same object. This should be an improvement as we currently have multiple instances of the exact (hopefully) same object when both the residual and jacobian are passed into matlab.
TODO:
- Incorporate changes from #1034 as this will be a clash
1. Try running with matlab controller and max runtime.
2. …
=> Enable max runtime in curve fitting

fitbenchmarking/cli/main.py
Fixes #1125 
1. Check fitbenchmarking help on the command line interface  
2.
3.
=> Add missing help spaces #1125

fitbenchmarking/core/results_output.py, fitbenchmarking/results_processing/fitting_report.py, fitbenchmarking/results_processing/tests/test_fitting_report.py
Fixes #1149 
Convert path to absolute path before passing around, convert back to relative before displaying.
Display in webbrowser using abs path on windows
1. Is the windows test passing?
=> Pass fitting_link as absolute path internally

fitbenchmarking/hessian/numdifftools_hessian.py, fitbenchmarking/hessian/scipy_hessian.py, fitbenchmarking/parsing/mantiddev_parser.py
While testing the #1231 PR, I found that it failed with the Scipy hessian.
This updates the scipy hessian to only evaluate on the whole x domain (so that the mantid jacobian can be calculated efficiently). A cache is used to allow only the minimum jacobian evaluations needed.
@AnthonyLim23 let me know if you're happy with these changes? I didn't want to change your PR without your feedback!
1.
2.
3.
=> Fix issues with scipy hessian and mantid jacobian

fitbenchmarking/controllers/bumps_controller.py, fitbenchmarking/controllers/lmfit_controller.py, fitbenchmarking/controllers/tests/test_controllers.py
Fixes #1247 
Assign numerical parameter names to variables within the context of the bumps controller.
These are only used in a mapping that has to be generated via the use of `eval` as bumps does not allow for **arg expansion.
1.
2.
3.
=> Updated bumps and lmfit controllers to be more robust against parameter names

fitbenchmarking/utils/fitbm_result.py, fitbenchmarking/utils/tests/test_fitbm_result.py, pyproject.toml
Fixes #1220 
Updates the relative runtime calculation in `FittingResult`
1. Run `fitbenchmarking -rt trim` to verify relative values are based on the selected metric.
2. Run `pytest fitbenchmarking/utils/tests/test_fitbm_result.py --test-type default` to verify all tests pass.
=> Updated relative runtime calculation in FittingResult

examples/options_template.ini, fitbenchmarking/results_processing/fitting_report.py, fitbenchmarking/templates/fitting_report_template.html
Fixes #1221 
Changes fitting report so that Emissions value is listed as 'N/A' when the emissions table option is not selected. I have also updated the `options_template.ini` so that the emissions table is not deactivated, as measuring emissions is no longer painfully slow.
1. Run Fitbenchmarking without emissions table option, and check fitting report.
2. 
3.
=> Fixed emissions display when not measured

fitbenchmarking/core/fitting_benchmarking.py, pyproject.toml
CodeCarbon v2.5.1 includes a fix for the [divide by zero error in `start_task()`](https://github.com/mlco2/codecarbon/issues/549), so the hack put in place to get around this in [this PR](https://github.com/fitbenchmarking/fitbenchmarking/pull/1285) can now be removed.
1. Run FitBenchmarking on Windows with emissions table selected and check that emissions results are produced
2.
3.
=> Removed codecarbon hack for avoiding div by zero

docs/source/users/checkpointing.rst, fitbenchmarking/utils/tests/test_checkpoint.py, pyproject.toml
Fixes #1313
Removed the numpy pin (as required by #1255). It was temporarily reintroduced because of a nlopt build issue. However, that has since been fixed. 
The checkpoint tests were also updated to skip matching the `_compressed` and `_decompressed` values of these 
`params = ['fin_y', 'r_x', 'jac_x', 'params', 'ini_y', 'x', 'y', 'e', 'sorted_idx', 'ini_params']`. This is because the values now differ because the checkpoint.json was created on a different version of python.
The `_compressed` and `_decompressed` methods are individually tested, so they are working fine on the same version of python.
But this may also mean that a checkpoint file created on a older version of python may not be decompressed correctly on the latest version of python.
1. The GitHub Actions should pass.
=> Removed numpy pin

fitbenchmarking/core/results_output.py, fitbenchmarking/core/tests/test_results_output.py
Fixes #1256 
Copies the formatting from the first plot chosen when multiple are displayed via dash.
1. Go to accuracy table page and click online plots (while dash is running)
2. Remove all lines and add them back in a random order so the colours are different
3. Check against the online plots on the runtime table page to make sure they disagree
4. Open the compare table and check that they update to match
=> Fix issue where perf profiles could be out of sync in dash

fitbenchmarking/core/results_output.py, fitbenchmarking/core/tests/test_results_output.py, fitbenchmarking/results_processing/tables.py, fitbenchmarking/utils/options.py, fitbenchmarking/utils/tests/test_options_generic.py
Fixes #1253 
Options now creates a uuid for every instance, and this is embedded in the dash urls.
If the uuid of the options file does not match the dash url, a message about using `--load-checkpoint` is displayed.
Existing plots will get an error saying the url is in the wrong format.
1. Try to recreate the issue as explained in my comment
=> Added error message for online plots that are unavailable

fitbenchmarking/results_processing/performance_profiler.py, fitbenchmarking/results_processing/tests/test_performance_profiler.py
Fixes #1240
Counts failures as an `np.inf` rather than `> 1e20`.
1. Run the test example from the comment in the issue and verify no failures
2. Run it with gradient_free as well and verify all fail correctly (gradient free requires bounds)
=> Fix issue where failures were incorrectly reported in performance profile

docs/source/users/BenchmarkProblems.rst
Change the locations of the data files to our github.io pages
Fixes #1373 
*NB* Needs https://github.com/fitbenchmarking/fitbenchmarking.github.io/pull/4 to be merged first
1. Check the download links on [this page](https://fitbenchmarking.readthedocs.io/en/stable/users/BenchmarkProblems.html) work
2. Check that the new links added (`Mantid_System_Test_Data`, `scripts`, and `synthetic_data`) work, and contain the expected data
=> Updated the location of external data files

Container/Containerfile
Fixes #1412
The new sscanss install was installing h5py but without the required `--no-binary` flag. Hopefully this solves it!
1.
2.
3.
=> Install h5py with --no-binary in container

.github/workflows/integration.yml
Fixes the failing integration [tests](https://github.com/fitbenchmarking/fitbenchmarking/actions/runs/13247847947/job/36980160567). Updated the workflow to use `actions/setup-python@v5` instead of the **conda** environment. Also added the default tests for Windows (Python 3.13).
1. The integration tests will pass. Can be verified [here](https://github.com/fitbenchmarking/fitbenchmarking/actions/runs/13249267189). The tests should also pass when this PR is approved.
=> Fixed failing integration test for Mac OS - Python 3.13

fitbenchmarking/templates/fitting_report_template.html, fitbenchmarking/templates/problem_summary_page_template.html
Updated the table template to separate out the variables and make them more readable at a glance.  
**Before**
**After**
1. Run `fitbenchmarking` and verify tables are updated in the fitting report and problem summary pages.
2. Run `fitbenchmarking -p examples/benchmark_problems/MultiFit -s mantid` and verify tables are updated for the multifit datasets.
**Note** - The fitted and best parameters are shown as lists. But this should not be the case. An issue has been created to fix this bug.
#1430
=> Updated table to improve readability of the initial, fitted and best parameters

fitbenchmarking/results_processing/performance_profiler.py
This is to check whether dash component ids contain any of the characters not allowed by Dash ( "." and "{" ) and remove these characters before creating the plot.
Fixes #1304 .
To check this, the path to the problems being run (provided in the command line) needs to include e.g. ".."  . Fitbenchmarking uses the path to determine the id to assign to Dash components. So the changes in this PR aim at removing characters not allowed by Dash (like ".") from the Dash component id, before creating the component.
I checked the changes by:
1. moving a folder with specific problems (e.g. SIF) to outside the folder "examples" . 
2. then running:    fitbenchmarking -p /home/letizia/fitbenchmarking/examples/../SIF
This only works through the changes in this PR. Otherwise Dash raises an error.
=> Added check/processing on dash component ids

fitbenchmarking/results_processing/base_table.py, fitbenchmarking/results_processing/compare_table.py, fitbenchmarking/results_processing/local_min_table.py
Fixes #1289
As mentioned in the issue, the cells are partially coloured when the accuracy in **infinity** and runtime is **finite**. This happens when `controller.eval_chisq` returns **infinity** because the fitting benchmark did not result in finding good parameters. The error code in this case is 2 which means that the software did not converge to a solution. 
This is technically not an error. I have updated the tables to show the results in this case as follows.
This is done so that the user can update the problem definition file to check the algorithm performance with different ranges of data or different starting conditions etc. Doing it this way also means that the result summary page is linked and the user can view the results of the fitting benchmark even though they are not …
=> Fixed the partial cell rendering when error flag is 2

fitbenchmarking/controllers/bumps_controller.py, pyproject.toml
It would be nice to have an explicit check to verify that private members are not accessed in the code base besides in test files for testing behaviour. A private member was being accessed in the `bumps` controller. The code has been updated to use the [labels()](https://github.com/bumps/bumps/blob/4af0401c27fc88ebe41b5745f24e9287779a2b84/bumps/fitproblem.py#L530) method instead of accessing **_parameters**.
1. run `ruff check .` and verify that **All checks passed!**
2. run `ruff format .` and verify no warnings are raised.
=> Added SLF ruleset to check private member access through ruff

fitbenchmarking/results_processing/base_table.py, fitbenchmarking/results_processing/tables.py, fitbenchmarking/results_processing/tests/expected_results/acc.html, fitbenchmarking/results_processing/tests/expected_results/compare.html, fitbenchmarking/results_processing/tests/expected_results/energy_usage.html, fitbenchmarking/results_processing/tests/expected_results/local_min.html, fitbenchmarking/results_processing/tests/expected_results/minimizer_dropdown.html, fitbenchmarking/results_processing/tests/expected_results/runtime.html, fitbenchmarking/templates/css/custom_style.css, fitbenchmarking/templates/js/table.js, fitbenchmarking/templates/table_template.html
Fixes #993 
https://github.com/user-attachments/assets/ba9686c2-231c-4f46-ae97-2a9273b47f09
1. Create an options file with the following content. Name the file `tmp.ini`. And run `fitbenchmarking -o tmp.ini`.
```
[FITTING]
software: bumps
scipy
scipy_ls
cost_func_type: weighted_nlls
nlls
num_runs: 1
max_runtime: 600
[MINIMIZERS]
bumps: lm-bumps
scipy-leastsq
scipy: Powell
CG
TNC
scipy_ls: lm-scipy
```
2. Verify new dropdown menus are visible for all the table.
3. Uncheck options from the new menus and verify that everything is updated as expected.
#1478
=> Added new dropdown menus for filtering the software and cost function results
