fitbenchmarking/example_runScripts.py, fitbenchmarking/fitting_benchmarking.py, fitbenchmarking/input_parsing.py
This comes after PR #19 
This fixes #15
The if statement reduces the terminal output and makes the program run more smoothly.
To test:
1. In fitbenchmarking/example_runScript.py change run_data = "neutron"
2. Run example_runScript.py in the mantidpython terminal
3. Check if the outputted tables are the neutron ones
4. Check in the terminal if the output is error messages from the try statement are still there
5. Repeat for the NIST data
=> Replaced the try statement with an if

fitbenchmarking/fitting_benchmarking.py
**Description of work:**
Fixed #29, i.e. best_fit not being defined before assignment sometimes, and moved the plotting algorithm that was initially embedded into do_fitting_benchmark_one_problem function into its own separate function.
**To test:**
1. Open the mantidpython console
2. Run example_runScript.py in the console by typing
`run /your_path/fitbenchmarking/fitbenchmarking/example_runScript.py`
3. Check if you are getting the same results as master
=> Best_fit not defined solved

README.md
1. Follow the instructions in README.md
2. Check if the installation folders are created and if the script runs, producing the same results as master.
=> Added documentation on how to install the fitbenchmarking script.

fitbenchmarking/example_runScripts.py, fitbenchmarking/fitting_benchmarking.py
Additionally, changed the order of the minimizers to increase readability
Fixes #31 
1. Make sure that in example_runScripts.py `run_data` is set to "nist".
2. Run example_runScripts.py in the mantidpython console.
3. Compare the results with the output you get from following the same steps in master branch.
=> Code now uses poisson distributed y data to fake observational errors

fitbenchmarking/test/ResultsOutputTest.py
Added unit tests for functions that display the results of the fits.
Run the test files in the mantidpython console and check if the tests are successful (if tests with fail in their name do fail, that is considered expected behaviour).
=> Results output tests

fitbenchmarking/fitting_benchmarking.py
Fixes #36 
1. Make sure that in example_runScripts.py `run_data` is set to "nist".
2. Run example_runScripts.py in the mantidpython console.
3. Compare the results with the output you get from following the same steps in master branch.
=> Made IF statement less convoluted.

fitbenchmarking/example_runScripts.py, fitbenchmarking/fitting_benchmarking.py, fitbenchmarking/post_processing.py, fitbenchmarking/results_output.py, fitbenchmarking/test_result.py
Deleted the redundant chi_squared calculations along with fixing some minor issues. Restructured the test_result object such that it only records one chi squared value. Added a function that calculates chi squared separately by using a vector of the differences between the actual data and the fit data (better when the project is extended beyond mantid).
1. In `example_runScripts.py` make sure that run_data is `"neutron"`.
2. Run the script in the mantidpython console.
3. Compare the results with the ones from master, they should be the same.
4. Change run_data to `"nist"`.
5. Repeat the process.
=> Deleted the redundant chi_squared calculations 

.github/PULL_REQUEST_TEMPLATE.md
This can be modified at a later date.
=> Created pull request template. 

fitbenchmarking/example_runScripts.py, fitbenchmarking/fitting_benchmarking.py, fitbenchmarking/input_parsing.py
Fixes #66 
Code can now handle results_dir input better.
1. Run `example_runScript.py` with different `results_dir`. These should include:
- results_dir = None
- results_dir = "Something"
- results_dir = 12
- results_dir = os.sep + "Something"
2. Check if the output is the same as master.
=> Improved how the script handles results_dir input

fitbenchmarking/example_runScripts.py, fitbenchmarking/fitting_benchmarking.py, fitbenchmarking/results_output.py
Fixes #57
Removed the problems empty array. The problem object data is included in the test_results object so there was no use for it to be passed separately.
1. Run `example_runScripts.py` in the mantidpython terminal.
2. Check if the produced tables are the same.
=> Removed the problems empty array as it was useless.

fitbenchmarking/fitting_benchmarking.py, fitbenchmarking/results_output.py, fitbenchmarking/test_result.py
Fixes #8 
Fixes #75
Visual display pages now show what was requested in the issue.
1. Run `example_runScript.py` in the mantidpython console.
2. Check if the links in the produced tables link to the right pages and if the pages display the correct things.
=> Added visual display pages for nist and neutron data

example_scripts/example_runScripts.py, fitbenchmarking/fitting_benchmarking.py, fitbenchmarking/input_parsing.py, fitbenchmarking/logging_setup.py, fitbenchmarking/plotHelper.py, fitbenchmarking/post_processing.py, fitbenchmarking/results_output.py, fitbenchmarking/test_result.py
Fixes #48 
As the title says, added comments, improved variable names and improved structure.
Note: Code still needs to be organised in modules, right now it is too messy and still kind of hard to understand.
1. Run `example_runScripts.py`  in the mantidpython console.
2. Check if the tables work properly.
=> Added comments and improved structure

fitbenchmarking/fitbenchmark_one_problem.py, fitbenchmarking/fitting/fit_algorithms.py, fitbenchmarking/fitting/mantid_utils.py, fitbenchmarking/fitting/minimizers.json, fitbenchmarking/fitting/plotting/plot_helper.py, fitbenchmarking/fitting/plotting/plots.py, fitbenchmarking/fitting_benchmarking.py, fitbenchmarking/parsing/fetch_data.py, fitbenchmarking/parsing/parse_neutron.py, fitbenchmarking/parsing/parse_nist.py, fitbenchmarking/result_processing/fitdetails_tbls.py, fitbenchmarking/result_processing/misc.py, fitbenchmarking/result_processing/numpy_restables.py, fitbenchmarking/result_processing/rst_table.py, fitbenchmarking/result_processing/visual_pages.py, fitbenchmarking/results_output.py, fitbenchmarking/utils/create_dirs.py, fitbenchmarking/utils/fit_misc.py, fitbenchmarking/utils/logging_setup.py, fitbenchmarking/utils/setup_problem_groups.py, fitbenchmarking/utils/test_problem.py, fitbenchmarking/utils/test_result.py
Fixes #88 
Added function descriptions.
1. Look through all the files and see if the function descriptions are satisfying.
=> Added function descriptions

.travis.yml
=> Added Travis yml file

benchmark_problems/Neutron_data/EVS14188-90_Gaussian_peaks_1.txt, benchmark_problems/Neutron_data/EVS14188-90_Gaussian_peaks_2.txt, fitbenchmarking/fitbenchmark_one_problem.py
Fixes #92 
Fixes #89 
Fixed some minor things in the visual display pages.
1. In the `mantidpython` console, run `example_runScripts.py`
2. Check all the links in the main tables to the visual display pages and make sure that they are fine.
=> Fixed visual display tables issues

fitbenchmarking/fitbenchmark_one_problem.py, fitbenchmarking/fitting/fit_algorithms.py, fitbenchmarking/fitting/mantid_utils.py, fitbenchmarking/fitting/tests/fit_algorithms_tests.py, fitbenchmarking/fitting/tests/mantid_utils_tests.py, fitbenchmarking/result_processing/fitdetails_tbls.py, fitbenchmarking/result_processing/tests/fitdetails_tbls_tests.py, fitbenchmarking/result_processing/visual_pages.py, fitbenchmarking/utils/test_result.py
Fixes #90 
Added a second table on the visual display page that lists the functional form and the final parameters of the best fit.
1. In the `mantidpython` terminal run `example_runScripts.py`.
2. Check if the results are like expected.
=> Created second table on the visual display page

fitbenchmarking/fitting/plotting/plot_helper.py, fitbenchmarking/fitting/plotting/plots.py
Fixes #79 
Increased the line width of the fits and put them above the data points using the zorder attribute.
1. In the `mantidpython` terminal run `example_runScript.py`.
2. Check if the plots are good enough.
=> Increased the visibility of the vd page plots

fitbenchmarking/fitting/mantid_utils.py
Fixes #38 
Documented the WISH problem ad hoc exception. The problem itself is much deeper and it does not concern the fitting benchmarking tool. The issue has to do with the WISH nexus files.
Look through the code and check if the comments are good enough.
=> Documented the WISH problem adhoc exception

build/utils/build_logger.py, fitbenchmarking/utils/logging_setup.py
Fixes #105 
Slightly improved the logging format such that it is more readable.
1. In the `mantidpython` terminal, run `example_runScript.py`.
2. Check if the output is satisfying.
=> Improved logging format

systests/generate_current_results.py, systests/tbl_comparison.py
Fixes #120 
The system tests folder name was changed and travis could not find where the tests were located. This is fixed now. Additionally, added some tolerance on the result comparison such that they are independent of os (only tested on ubuntu 14 and 18).
Approve and see if the cron job runs successfully.
=> refs #120 fixed system test

example_scripts/example_runScripts.py, example_scripts/example_runScripts_expert.py, fitbenchmarking/fitting_benchmarking.py, fitbenchmarking/parsing/parse_fitbenchmark_data.py
Adds condition to check if fit_parameters is present in native fitbenchmark data format.
1. Check to see if example scripts run
=> Removing fit_parameter bug in EVS14188* data

README.md
Fixes #173 
1. Check if the added contents are satisfactory and understandable
2. Test the on macOS computers to verify the instructions
=> Update README.md to contain instructions for macOS users

.gitignore, fitbenchmarking/utils/logging_setup.py
Addition to Fixes #110
1. Run `example_runScripts.py` and verify the results.
2. Run `example_runScripts.py` with intentional exceptions and observe the `fitbenchmarking.log` file and the console.
=> Logging on console

fitbenchmarking/parsing/base_fitting_problem.py, fitbenchmarking/parsing/parse_fitbenchmark_data.py, fitbenchmarking/parsing/parse_nist_data.py, fitbenchmarking/parsing/tests/test_parse_fitbenchmark_data.py, fitbenchmarking/parsing/tests/test_parse_nist_data.py
Fixes #161 
1. Run `example_runScripts.py` and verify the results
=> Remove the attribute ref_residual_sum_sq

example_scripts/example_runScripts.py, fitbenchmarking/fitting/plotting/plots.py, fitbenchmarking/fitting/scipy/main.py
Fixes #124 
1. Run `example_runScripts.py` with `scipy` selected as the software option and observe the results on the html files generated
=> Scipy starting guess plots

fitbenchmarking/fitting/plotting/plot_helper.py
Fixes part of #242 
Changes sorting routine in `fitbenchmarking/fitting/plotting/plot_helper.py` to use argsort
1. Check examples scripts run
2. Tests passes
=> Update plotting/plot_helper to use numpy.argsort

fitbenchmarking/fitting/plotting/plot_helper.py
Fixes #251 
Removes no handles warning in plotting
1. Run example script
=> 251 removes no handles warning in plotting

fitbenchmarking/fitbenchmark_one_problem.py, fitbenchmarking/fitting/misc.py, fitbenchmarking/fitting/tests/test_misc.py
Fixes #246 
Adds errors to `compute_chisq` function to enable weighted chisq.
=> Adding weighted chi squared

fitbenchmarking/fitting/plotting/plot_helper.py
Fixes #245 
1. Set `use_errors = False` in an example script that calls Mantid
2. Check the tables are generated correctly
=> Amend conditions for zero or no errors

.travis.yml, build_ralfit.sh, docs/source/users/getting_started.rst, docs/source/users/options.rst, fitbenchmarking/fitbenchmark_one_problem.py, fitbenchmarking/fitbenchmarking_default_options.json, fitbenchmarking/fitting/controllers/ralfit_controller.py, fitbenchmarking/fitting/tests/test_controllers.py
Resolves #215  
1. Add `ralfit` to the software list in an example script
2. Check output is as expected (especially on `simple_tests`)
=> 215 Adding RALfit

.travis.yml
Fixes #288 
fixed by removing no longer used build instructions
1. Check that there are no environment variables in Travis-CI Setting for this repository 
2. Check that build passes
=> remove travis-ci settings env vars

docs/source/contributors/extending_fitbenchmarking.rst, fitbenchmarking/fitbenchmark_one_problem.py, fitbenchmarking/fitting/controllers/controller_factory.py, fitbenchmarking/fitting/tests/test_controllers.py
Fixes #273
Adds a factory implementation for the Controllers
=> 273 controller factories

fitbenchmarking/fitting_benchmarking.py, systests/generate_current_results.py
Addresses the main part of #291.
Note this does not close the issue but aims to fix the badge on the home screen.
1. Check that the sys tests passed
=> 291 fix sys test

docs/source/users/options.rst, fitbenchmarking/fitbenchmarking_default_options.json, fitbenchmarking/fitting/controllers/ralfit_controller.py, fitbenchmarking/fitting/tests/test_controllers.py
Fixes #297, #286.  Also:
- returns a result when an exception is thrown by RALFit due to the solution not being found
- minor adjustments to docs
1. add ralfit to the `software` list in the `example_runScripts.py` or similar
2. run on a range of example cases
3. check results are as expected (particularly with `simple_tests`)
**Function**: Does the change do what it's supposed to?
**Tests**: Does it pass? Is there adequate coverage for new code?
**Style**: Is the coding style consistent? Is anything overly confusing?
**Documentation**: Is there a suitable change to documentation for this change?
**Bonus**: I'm not sure the exception handling is done in the best way.  Could the reviewer(s) look closely at this -- suggestions for improvements very welcome!
=> RALFit weights and options

docs/source/users/options.rst, fitbenchmarking/fitbenchmarking_default_options.json, fitbenchmarking/fitting/controllers/minuit_controller.py, fitbenchmarking/fitting/tests/test_controllers.py, setup.py
Fixes #166 
1. Add `minuit` as a software in, e.g., `example_runScripts.py`
2. Check results are consistent with other minimizers
=> Adding CERN's minuit solver

systests/generate_current_results.py, systests/tbl_comparison.py
`flake8` now passes for `systests`. ping #238 
1.
2.
3.
=> flake8 systests

example_scripts/example_runScripts.py, fitbenchmarking/fitbenchmark_one_problem.py, fitbenchmarking/fitting_benchmarking.py
Fixes #331 
Adds information which minimizer is running.
1. Formatting of runtime output is ok?
=> Adds runtime infomation 

docs/source/conf.py, docs/source/contributors/extending_fitbenchmarking.rst, fitbenchmarking/fitting/controllers/dfogn_controller.py, fitbenchmarking/fitting/controllers/minuit_controller.py, fitbenchmarking/fitting/controllers/ralfit_controller.py, fitbenchmarking/parsing/fitting_problem.py, fitbenchmarking/parsing/tests/test_fitting_problem.py
Fixes #294 
Creates eval_r, eval_r_norm, and eval_j for evaluationg the residual, the square of the l2 norm for the residual and an approximation to the jacobian respectively.
Note: During this I observed that Minuit fails when running Muon, however this is also happening on master.
1. Check consistency with master
=> 294 move reused methods out of controllers

docs/source/users/options.rst, examples/options_template.ini, fitbenchmarking/results_output.py, fitbenchmarking/utils/default_options.ini, fitbenchmarking/utils/fitbm_result.py, fitbenchmarking/utils/options.py, fitbenchmarking/utils/tests/test_options.py
Fixes #137 
Adds additional table which compares runtime and accuracy in one place. 
1. Check combined colours are consistent with runtime and accuracy separately 
=> Adding comparison tables

fitbenchmarking/fitting/controllers/base_controller.py, fitbenchmarking/utils/default_options.ini
Fixes #202 
1. Check answers are the same (unless the clipping has kicked in....)
2. Check the change in the comments to the code/ini file are clear enough
=> Clip errors below 1e-8, and add explaination

fitbenchmarking/fitting/controllers/sasview_controller.py
Fixes #359.
- Checks for success before accessing `self._bumps_result`.
- Changes `self._bumps_results` to `self._bumps_result` in `__init__`.
1. run example script (with SASView) on a suitable test set
2. observe results
=> 359 bumps fix

fitbenchmarking/fitting/controllers/scipy_controller.py
Fixes #301 
Swaps `scipy` `curve_fit` with `least_squares` which gives more information to report in future tables
1. Check both weighted and unweighted results do not change for each data type
=> Implementing scipy least_squares

examples/benchmark_problems/CUTEst/META.txt, examples/benchmark_problems/Muon/META.txt, examples/benchmark_problems/NIST/average_difficulty/META.txt, examples/benchmark_problems/NIST/high_difficulty/META.txt, examples/benchmark_problems/NIST/low_difficulty/META.txt, examples/benchmark_problems/Neutron/META.txt, examples/benchmark_problems/SAS_modelling/1D/META.txt, examples/benchmark_problems/simple_tests/META.txt, fitbenchmarking/cli/main.py, fitbenchmarking/utils/misc.py
Fixes #345
Adds optional metadata file where the first line is the label for the dataset
1. Try with and without a META.txt file
=> Issue #345: Add META file for each dataset and use first line as label

fitbenchmarking/HTML_templates/blank_page.html, fitbenchmarking/core/results_output.py
Fixes #388 
Added blank template which is used to generate the results tables with the style sheet attached.
1. Check the new table style is consistent with the other html pages
=> Adding style sheet to tables

fitbenchmarking/parsing/fitbenchmark_parser.py
Fixes #395 
Re-implements function parser to handle brackets better
1. Test against a variety of brackets combinations and check that it only raises an exception when you pass in an erroneous function.
2. Test results are correct for functions where possible
=> Issue #395: Rewrite parser to improve bracket handling

examples/all_softwares.ini, examples/options_template.ini, fitbenchmarking/HTML_templates/problem_index_page.html, fitbenchmarking/core/results_output.py, fitbenchmarking/utils/default_options.ini, fitbenchmarking/utils/fitbm_result.py
Fixes #401 
Adds an additional table which indicates whether the software converges to a local minimum
1. Check table is consistent.
=> Local minimizer table

fitbenchmarking/core/results_output.py, fitbenchmarking/results_processing/support_page.py
Fixes #412 
Renames visual pages to support pages
1. Check there is no mention of visual page.
=> Rename visual to support pages

fitbenchmarking/controllers/base_controller.py, fitbenchmarking/controllers/dfogn_controller.py, fitbenchmarking/controllers/gsl_controller.py, fitbenchmarking/controllers/mantid_controller.py, fitbenchmarking/controllers/minuit_controller.py, fitbenchmarking/controllers/ralfit_controller.py, fitbenchmarking/controllers/sasview_controller.py, fitbenchmarking/controllers/scipy_controller.py, fitbenchmarking/controllers/tests/test_controllers.py, fitbenchmarking/core/fitbenchmark_one_problem.py, fitbenchmarking/core/fitting_benchmarking.py, fitbenchmarking/parsing/fitting_problem.py, fitbenchmarking/parsing/tests/test_fitting_problem.py, fitbenchmarking/results_processing/plots.py
Fixes #385 
Move data corrections out of controller and into fitting problem
1. This should not change anything
=> Issue #385: Move data corrections from controller to fitting problem

docs/source/contributors/structure.rst
Filled in structure documentation
1. Read and check that it makes sense
=> Issue #410: Complete first draft of file structure docs

fitbenchmarking/cli/main.py, fitbenchmarking/controllers/base_controller.py, fitbenchmarking/controllers/controller_factory.py, fitbenchmarking/controllers/dfo_controller.py, fitbenchmarking/controllers/gsl_controller.py, fitbenchmarking/controllers/mantid_controller.py, fitbenchmarking/controllers/minuit_controller.py, fitbenchmarking/controllers/ralfit_controller.py, fitbenchmarking/controllers/sasview_controller.py, fitbenchmarking/controllers/scipy_controller.py, fitbenchmarking/core/fitbenchmark_one_problem.py, fitbenchmarking/core/fitting_benchmarking.py, fitbenchmarking/core/results_output.py, fitbenchmarking/parsing/base_parser.py, fitbenchmarking/parsing/fitbenchmark_parser.py, fitbenchmarking/parsing/fitting_problem.py, fitbenchmarking/parsing/nist_data_functions.py, fitbenchmarking/parsing/nist_parser.py, fitbenchmarking/parsing/parser_factory.py, fitbenchmarking/results_processing/plots.py, fitbenchmarking/results_processing/support_page.py, fitbenchmarking/results_processing/tables.py, fitbenchmarking/utils/fitbm_result.py, fitbenchmarking/utils/misc.py, fitbenchmarking/utils/options.py
Fixes #236 
Updated all docstrings so that they are up to date with the function and respect the sphinx style.
=> Issue 236: Update all docstrings

.pylintrc, fitbenchmarking/utils/tests/test_fitbm_result.py
Ping #290 
Adds test to fitbenchmarking results object
1. Check test coverage
=> Adding results object tests

docs/source/extending/outputs/templates.rst
Fixes #450 
Filled in extending templates page.
1. Proof read
=> Issue #450: Fill in extending templates docs

docs/source/extending/outputs/tables.rst
Fixes #449
Updated extending tables docs to reflect the current state.
Included reference to #431 
Added info to #431.
1. Proof read docs.
=> Issue #449: Update extending tables docs

fitbenchmarking/cli/tests/test_exception_handler.py
Fixes #459 
Addes tests for the exception handler.
1. Check that it passes and coverage is good.
=> Issue #459: Add tests for exception handler.

.travis.yml, build_gsl.sh, docs/source/users/install_instructions/externals/gsl.rst
Fixes #451 
Adding GSL installation docs
1. Check docs are adequate 
=> Adding GSL installation docs

docs/source/concept/index.rst, docs/source/concept/what.rst, docs/source/users/index.rst, docs/source/users/tutorials.rst
Fixes #501 
Removed what?  and tutorial sections from the docs.
1. check the docs compile and look ok
2.
3.
=> 501 remove placeholders

fitbenchmarking/utils/log.py
Fixes #515 
Removes multiple printing from logger
1. Check that there is only one thing printed to the console.
=> Removes multiple printing within logger

fitbenchmarking/core/results_output.py, fitbenchmarking/results_processing/tables.py
Fixes #519 
1. run fitbenchmarking on Windows, and check all works
2. run fitbenchmarking on Linux, and check all works
=> Add encoding info to suppress windows error message

fitbenchmarking/parsing/parser_factory.py
Fixes #528 
1. check linting tests pass
=> Change line->lines and l->line

.travis.yml
=> Fix coveralls/travis reporting

build_cutest.sh
Fixes #586 
1. Check travis builds correctly
=> accommodate change in optrove build options

fitbenchmarking/parsing/cutest_parser.py
Fixes #610 
1. Check that SIF problems run correctly
=> use pycutest's cache clearing functions

fitbenchmarking/cli/main.py, fitbenchmarking/utils/options.py, fitbenchmarking/utils/tests/test_options_generic.py
Fixes #618 
Adds options reset
1. Check that multiple problem groups run correctly
=> Options reset

setup.py
Fixes #665 
This may fix #660 as well. 
1. Check the tests and installation work as before
=> Removing h5py from setup.py

azure-pipelines.yml, fitbenchmarking/results_processing/support_page.py, fitbenchmarking/results_processing/tests/test_support_page.py
Fixes #669 
Allows tests to be run on Azure and report the correctly whether the tests pass or fail.
1. Check that the tests pass
=> Fixing Azure tests

fitbenchmarking/cli/main.py
Fixes #674 
Copies the fonts directory into the results directory
1. Check the buttons on the index pages work
=> Webpage buttons

.github/workflows/main.yml
Fixes #714 
1. Does the linting test run?
=> Issue #714: Install gsl in tests

.github/workflows/release.yml
From: https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
and: https://packaging.python.org/tutorials/packaging-projects/
=> Add github action to push a release to PyPI if tagged

Docker/BasicInstall/Dockerfile, Docker/FullInstall/Dockerfile
For the new iminuit, we need cmake in the basic docker
=> Add cmake to docker for iminuit2.x

fitbenchmarking/utils/output_grabber.py
Fixes check for 'debug' mode.
Fixes #737
1. Try running with each value for option `external_output: ...` with and and without this change.
=> Fix exit check

fitbenchmarking/utils/create_dirs.py, fitbenchmarking/utils/exceptions.py, fitbenchmarking/utils/misc.py, fitbenchmarking/utils/options.py, fitbenchmarking/utils/output_grabber.py, fitbenchmarking/utils/tests/test_create_dirs.py, fitbenchmarking/utils/tests/test_logger.py, fitbenchmarking/utils/tests/test_misc.py, fitbenchmarking/utils/tests/test_options_generic.py, fitbenchmarking/utils/tests/test_options_plotting.py, fitbenchmarking/utils/tests/test_output_grabber.py
Fixes #789 
1. Check linting errors/warnings are 0
2. Check code still works as expected
3. Check docstrings added accurately describe the code
=> fix linting errors/warnings in utils

fitbenchmarking/results_processing/acc_table.py, fitbenchmarking/results_processing/base_table.py, fitbenchmarking/results_processing/compare_table.py, fitbenchmarking/results_processing/local_min_table.py, fitbenchmarking/results_processing/performance_profiler.py, fitbenchmarking/results_processing/plots.py, fitbenchmarking/results_processing/runtime_table.py, fitbenchmarking/results_processing/tables.py, fitbenchmarking/results_processing/tests/test_performance_profiler.py, fitbenchmarking/results_processing/tests/test_plots.py, fitbenchmarking/results_processing/tests/test_support_page.py, fitbenchmarking/results_processing/tests/test_tables.py
Fixes #788 
1. Check that there are no pylint or flake8 errors/warnings
2. Check nothing is broken by changes
=> fix linting errors and warnings in results

fitbenchmarking/controllers/base_controller.py, fitbenchmarking/controllers/bumps_controller.py, fitbenchmarking/controllers/controller_factory.py, fitbenchmarking/controllers/dfo_controller.py, fitbenchmarking/controllers/gsl_controller.py, fitbenchmarking/controllers/levmar_controller.py, fitbenchmarking/controllers/mantid_controller.py, fitbenchmarking/controllers/minuit_controller.py, fitbenchmarking/controllers/ralfit_controller.py, fitbenchmarking/controllers/scipy_controller.py, fitbenchmarking/controllers/scipy_ls_controller.py, fitbenchmarking/controllers/tests/test_controllers.py
Fixes #765
1. Run pylint and flake8 to check no errors or warnings
2. Check changes make sense and everything still works as expected
=> 765 Controllers linting fixes

fitbenchmarking/jacobian/analytic_jacobian.py, fitbenchmarking/jacobian/default_jacobian.py, fitbenchmarking/jacobian/jacobian_factory.py, fitbenchmarking/jacobian/numdifftools_jacobian.py, fitbenchmarking/jacobian/scipy_jacobian.py, fitbenchmarking/jacobian/tests/test_jacobian.py, fitbenchmarking/results_processing/tests/test_tables.py
Fixes #786
1. Try running flake8 and pylint on the Jacobians dir
=> Fix linting on Jacobians

docs/source/users/problem_definition_files/native.rst
Fixes #808
1. Check that link now works
=> Fix dead link

docs/source/users/options/fitting_option.rst
=> Remove use_errors option from docs

docs/source/users/options/fitting_option.rst, docs/source/users/options/minimizer_option.rst, examples/all_softwares.ini, fitbenchmarking/controllers/matlab_stats_controller.py, fitbenchmarking/controllers/tests/test_controllers.py, fitbenchmarking/systests/linux_expected_results/matlab.txt, fitbenchmarking/systests/test_regression.py, fitbenchmarking/utils/options.py
Fixes #817 
1. Run FitBenchmarking with matlab_stats fitting software with various fitting problems
=> Add Matlab Statistics Toolbox Fitting

docs/source/concept/index.rst, docs/source/concept/why.rst, docs/source/contributors/guidelines.rst, docs/source/contributors/structure.rst, docs/source/contributors/workflow.rst, docs/source/extending/outputs/templates.rst, docs/source/extending/parsers.rst, docs/source/users/BenchmarkProblems.rst, docs/source/users/install_instructions/externals.rst, docs/source/users/install_instructions/fitbenchmarking.rst, docs/source/users/notes.rst, docs/source/users/options/fitting_option.rst, docs/source/users/options/jacobian_option.rst, docs/source/users/options/minimizer_option.rst, docs/source/users/problem_definition_files/native.rst
Fixes #850 
1. Check that fixes are correct
2.
3.
=> fix spelling mistakes in docs

fitbenchmarking/templates/table_style.css
=> Freezing index column and header row

fitbenchmarking/results_processing/tests/expected_results/acc.html, fitbenchmarking/results_processing/tests/expected_results/compare.html, fitbenchmarking/results_processing/tests/expected_results/local_min.html, fitbenchmarking/results_processing/tests/expected_results/runtime.html
Reformatted html to pass tests.
Fixes #867
1. Do tests pass?
=> Reformat to pass with linted html

fitbenchmarking/parsing/fitting_problem.py, fitbenchmarking/results_processing/base_table.py
Pylint was complaining that `for i in range(len(...))` should be changed to `for i, _ in enumerate(...)`.
In this case I disagreed but have changed it so that the meaning of `len(...)` is more explicit to fix the issue.
I also fixed a linting issue with using a list as a default value.
Fixes #865 
1. Check that pylint passed (using version >= 2.9.3)
=> Linting fixes

docs/source/users/options/minimizer_option.rst
Fixes #862
1. Check that the scipy_go algorithm links in the docs are now rendered correctly
=> Fix scipy_go link formatting

fitbenchmarking/jacobian/analytic_jacobian.py, fitbenchmarking/jacobian/tests/test_jacobian.py
Fixes #886 
1. Run fitbenchmarking with analytic and scipy jacobian options selected and check that results are consistent
2.
3.
=> fix analytic jacobian for hellinger_nlls

docs/source/users/options/plotting_option.rst, docs/source/users/output/index.rst
Fixes #759 
1. Check docs make sense
2.
3.
=> Add info about accessing plots of fit

fitbenchmarking/controllers/ralfit_controller.py, fitbenchmarking/controllers/tests/test_controllers.py
Fixes #888 
1. Run RALFit minimizers with analytic `hes_method` selected. 
2.
3.
=> Add Hessians for RALFit

fitbenchmarking/jacobian/tests/test_jacobian.py
Fixes #908 
1. Check that jacobian tests still pass and that analytic jacobians for each cost function are correct
2.
3.
=> Improve analytic jacobian tests

fitbenchmarking/controllers/matlab_curve_controller.py
In the matlab_curve controller, `algorithm_check` was still being set within `__init__`, this has now been changed so that `algorithm_check` is set as a class attribute which is consistent with all other controllers. 
1. 
2.
3.
=> Move algorithm_check in matlab_curve controller for consistency

.github/workflows/main.yml, pyproject.toml, setup.py
This PR fixes the error causing Pygsl not to install using pip:
1. Make sure the tests pass.
=> Fix Pygsl installation error

docs/source/users/options/plotting_option.rst
This PR makes some small fixes to the user documentation.
Fixes #1004
1.
2.
3.
=> Minor documentation fixes

docs/source/users/options/minimizer_option.rst, fitbenchmarking/controllers/mantid_controller.py, fitbenchmarking/controllers/tests/test_controllers.py, fitbenchmarking/utils/options.py
Fixes #1019 
1. Read through the docs and check they are clear
2. Run fitbenchmarking with the FABADA option under mantid, and check it gives reasonable answers
=> add support for the FABADA method

fitbenchmarking/results_processing/base_table.py
Fixes issue where minimizer toggling was using old naming conventions.
1. Run fb and toggle some names with jacobians
2. Verify behaviour is consistent with expectations
=> Update minimizer names in dropdown

setup.py
Fixes #1029
1. Does it still install?
2. Does it stop old python versions?
=> Add a minimum python version

fitbenchmarking/cost_func/tests/test_cost_func.py
It looks like some dependency has been updated and now one of our tests is failing as the test is too precice?
Fixes the tests on master
1. Do the tests pass?
2.
3.
=> Fix the poisson cost func test

docs/source/users/options/fitting_option.rst, docs/source/users/running.rst
=> Fix "external software" marked as "default" #1056

fitbenchmarking/cost_func/base_cost_func.py, fitbenchmarking/cost_func/hellinger_nlls_cost_func.py, fitbenchmarking/cost_func/nlls_cost_func.py, fitbenchmarking/cost_func/poisson_cost_func.py, fitbenchmarking/cost_func/weighted_nlls_cost_func.py
Fixes #1074 
1. Check the formating of `hes_res` in all the cost functions is correct
=> Fix docstring formatting

.github/workflows/main.yml, .github/workflows/nightly.yml, .github/workflows/release.yml
Fixes the warnings on gh actions
=> Update the versions of our github actions

Docker/FullInstall/Dockerfile, docs/source/contributors/structure.rst
Fixes #1086 
Doesn't update the mantid version, so will open a new issue for that.
1.
2.
3.
=> reorder dockerfile and update docs

fitbenchmarking/controllers/horace_controller.py
=> remove redundant herbert_off

docs/source/users/install_instructions/externals.rst
=> Improve the matlab installation docs #983

fitbenchmarking/systests/linux_expected_results/all_parsers.csv, fitbenchmarking/systests/test_regression.py, fitbenchmarking/utils/tests/test_options_minimizers.py
=> Add more tests for fb minimizers #1137

.coveragerc
Add matlab files to omitted list in coveralls
Fixes #1140 
1.
2.
3.
=> Omit matlab files fom coverage reports

fitbenchmarking/templates/css/table_style.css
I noticed the sidescrolling of tables got broken along the line.
This fixes it.
1. Compare tables from master and this branch. Try different window sizes to see scrolling issue
=> Fix empty cell scrolling behaviour in tables

setup.py
Fixes #1173 
Pin CodeCarbon version to avoid dependency issue
1. pip install
2. do a simple run (e.g. ```fitbenchmarking -p benchmark_problems/NIST/low_difficulty/ -s scipy_ls```) 
=> Pin codecarbon

.readthedocs.yaml, docs/requirements.txt
Fixes #1178 
1. Check the tests pass
2. Check the docs display correctly on rtd
3.
=> Add a readthedocs configuration file for online documentation

ci/prep_and_tag_release.sh
Fixes bash script if statement
=> Fix bash syntax

.github/PULL_REQUEST_TEMPLATE.md, .github/release.yml, docs/source/contributors/workflow.rst
Fixes #1177 
1. Read the docs, and check they make sense
2. Read through the yaml to check it makes sense
3. Read through the proposed new PR template.
=> Added support for automated release notes

fitbenchmarking/core/results_output.py, fitbenchmarking/results_processing/performance_profiler.py, fitbenchmarking/results_processing/plots.py, fitbenchmarking/results_processing/tests/test_performance_profiler.py, fitbenchmarking/templates/css/custom_style.css, fitbenchmarking/templates/table_template.html
Fixes #1180 .
- Updated the code so that performance profiles are generated using plotly rather than matplotlib.
- Added a warning for the users in the table templates (just below the performance profiles). This is specify that the performance profile plot does not get recalculated when they remove a certain line/minimizer from the graph by clicking on the legend (removing line is now possible thanks to plotly).
Just run fitbenchmarking and check the performance profiles in the table pages. It should be possible to:
1. Zoom in and out
2. Remove traces and add them back in using the legend
3. See points coordinates and minimizer name wheh hovering over the lines
=> Replaced matplotlib with plotly as the engine for generating performance profiles

fitbenchmarking/cli/main.py
Fixes #1197 .
Changed the default runtime metric in parser from "mean" to "". 
If anything different from "" is specified, this then overwrites the runtime_metric passed in the options file (if anything is passed).
1.
2.
3.
=> Fixed issue with parser overwriting any runtime metric passed through options file.

fitbenchmarking/core/results_output.py, fitbenchmarking/core/tests/test_results_output.py, fitbenchmarking/results_processing/performance_profiler.py, fitbenchmarking/results_processing/plots.py, fitbenchmarking/results_processing/problem_summary_page.py, fitbenchmarking/results_processing/tests/test_performance_profiler.py, fitbenchmarking/results_processing/tests/test_plots.py
Fixes #1202 
- Fixed the path to plotly.js in the function that writes plots to html.
- Introduced a test for the function, to check the size of the produced html file (generally it's smaller than 50KB when plotly.js is not included, while it's around 3000KB when this is not the case).
1.
2.
3.
=> Fixed function for writing plots to html and added test

fitbenchmarking/results_processing/acc_table.py, fitbenchmarking/results_processing/base_table.py, fitbenchmarking/results_processing/compare_table.py, fitbenchmarking/results_processing/emissions_table.py, fitbenchmarking/results_processing/local_min_table.py, fitbenchmarking/results_processing/performance_profiler.py, fitbenchmarking/results_processing/runtime_table.py, fitbenchmarking/results_processing/tables.py, fitbenchmarking/results_processing/tests/test_base_table.py, fitbenchmarking/results_processing/tests/test_performance_profiler.py, fitbenchmarking/results_processing/tests/test_tables.py
Fixes #1196
Adds a performance profiler for the emissions table (and generalises the code so that extending this will be easier in future).
As far as I'm aware this is a bug that was unexpected so no docs changes needed.
Open questions this raises:
- Are we happy with just having acc and runtime on the compare table page?
I don't think we should add more to the table but the pp could be put in easily if we wanted to.
- Is it worth doing something differently with the local min?
Currently it shows acc and runtime pp. It would make more sense to show a bar chart of successes since it's a binary result.
1. Look for the new emissions table after generating the results. It should be similar but marginally different to runtime.
=> Fixed bug where the emissions table showed a runtime performance profile

fitbenchmarking/templates/js/table.js, fitbenchmarking/templates/table_template.html
=> Fixed issue with back page button not working after introducing Dash. 

docs/requirements.txt
=> Bumped sphinx version for docs

.github/workflows/main.yml, fitbenchmarking/systests/test_regression.py
=> Try to fix coveralls again

.gitignore, .pre-commit-config.yaml, docs/source/contributors/guidelines.rst, pyproject.toml
Adds a pre-commit config file, and documents how to activate it.
@AnthonyLim23 In the example you sent you have this:
```
```
But no `.flake8`... know if I need to be a bit more careful about settings here?
1.
2.
3.
=> Add precommit config

fitbenchmarking/controllers/lmfit_controller.py, fitbenchmarking/controllers/mantid_controller.py
Two of the current FitBenchmarking minimizers, `emcee` and `FADABA` use MCMC methods so have now been added to this category of optimization algorithms
1.
2.
3.
=> Added emcee and FABADA as Bayesian minimizers

.github/workflows/release.yml
=> Updated build commands in release workflow

.github/workflows/main.yml, fitbenchmarking/core/fitting_benchmarking.py, fitbenchmarking/core/tests/test_fitting_benchmarking.py
Fixes #1284 
Injected a short delay (1e-10s) to the codecarbon initialisation so that it does not register a duration of 0 seconds when starting a task. If the duration is zero, there is a division by zero error.
1. Do emissions results work on Windows without crashing now?
=> Improved performance of codecarbon calls on Windows machines

fitbenchmarking/core/fitting_benchmarking.py
=> Added cost function type to logs

fitbenchmarking/controllers/base_controller.py
Fixes #1296 
Adds a couple of sentences to explain what the `algorithm_check` dictionary is used for, and how to find more information on the different categories
1.
2.
3.
=> Added more detail to algorithm_check docs

fitbenchmarking/core/fitting_benchmarking.py, fitbenchmarking/core/tests/test_fitting_benchmarking.py
Fixes #1195 
Switches out `warnings.warn` for `LOGGER.warning` to avoid the progress bar being printed and other formatting issues.
1.
2.
3.
=> Fixed output formatting errors

.github/workflows/main.yml, pyproject.toml
Fixes #1308
1. Check the GitHub actions
=> Pinned numpy

.github/workflows/install.yml, .github/workflows/main.yml
I work through a fork and I noticed that the scheduled weekly GitHub actions for `Tests` and `PYPI` are running on my fork as well. And here are the OS usage summaries for the latest runs. 
- `Tests`
- `PYPI`
The [PYPI](https://github.com/RabiyaF/fitbenchmarking/actions/runs/10991099166) install passes but I don't think these tests need to be run on forks as well.
The [Tests](https://github.com/RabiyaF/fitbenchmarking/actions/runs/10991041833) fail because of the **Publish Test Results** step. Again, I don't think these need to be duplicated on forks as long as there is activity on the main repo.
Turning off these unnecessary runs might save a small amount of ⚡ 
1. Can only be tested after merging, the test will not run on my fork next week. But everything else should remain the same.
=> Updated workflows to stop scheduled tests running on forks

.github/workflows/main.yml, .github/workflows/release.yml
Fixes the failing tests. The tests for python `3.x` were failing because the runners are now installing python `3.13`. I will open another issue to explore what that issue is with python `3.13`. One of the average difficulty problems is failing with an unclear error message.
1. The Github actions will now run on `3.12` instead of `3.x`. All the test will pass.
#1342
=> Pinned the maximum python version for the GitHub actions

fitbenchmarking/parsing/fitbenchmark_parser.py, fitbenchmarking/parsing/tests/test_parsers.py
Fixes #1276 
1. Run `pytest fitbenchmarking/parsing/tests/test_parsers.py -k TestFitbenchmarkParser`
=> Fixed the problem name bug

fitbenchmarking/utils/options.py, fitbenchmarking/utils/tests/test_options_minimizers.py
Fixes #1335 
1. run `pytest fitbenchmarking/utils/tests/test_options_minimizers.py -k UserMininimizerOptionTests`
=> Fixed the bad error msg

fitbenchmarking/results_processing/base_table.py, fitbenchmarking/templates/table_descriptions.rst, fitbenchmarking/utils/fitbm_result.py, fitbenchmarking/utils/tests/test_fitbm_result.py
Fixes #1233 
1. run `pytest fitbenchmarking/utils/tests/test_fitbm_result.py `
=> Fixed the perfect fit divide by zero error

.pre-commit-config.yaml, fitbenchmarking/cli/tests/test_checkpoint_handler.py, fitbenchmarking/controllers/lmfit_controller.py, fitbenchmarking/results_processing/base_table.py, fitbenchmarking/results_processing/tests/test_base_table.py, fitbenchmarking/results_processing/tests/test_fitting_report.py, pyproject.toml
Fixes #1327 
1. The tests should all pass on the GitHub runners.
=> Added the C4 ruleset to ruff

fitbenchmarking/parsing/fitting_problem.py, fitbenchmarking/parsing/tests/test_fitting_problem.py
Fixes #1232
Fixed the bug and added a test for `ini_y`. Also refactored some tests to remove extra variables.
1. run `fitbenchmarking -p examples/benchmark_problems/MultiFit -s mantid` and verify Multifit data will produce an output without an error.
=> Fixed the Multifit problem bug

.github/workflows/integration.yml, .github/workflows/main.yml, README.md
Fixes #1340 
Fixes #1051
Fixes #1292
The full tests take slightly longer now, therefore I have removed the `windows` tests from the main workflow. This means that they won't run with every commit push. This will reduce the runtime to the main workflow by ~15 minutes each time.
Instead, I have moved the `windows` and `mac` tests to an integration workflow. This will only run when a PR is approved. It will be less frequent and will save energy overall.
1. The integration workflow should pass. This can be verified [here](https://github.com/fitbenchmarking/fitbenchmarking/actions/runs/11599330825)
=> Added integration workflow

.github/workflows/main.yml
Pushes coveralls updates even on failed tests.
1.
2.
3.
=> Upload coveralls even after failed tests

fitbenchmarking/templates/js/table.js
Fixes #1383 
1. Run `fitbenchmarking` and navigate to the main table page. 
2. Uncheck the Problem Size Column.
3. Verify that the header of the error table is not hidden.
=> Fixed the disappearance of the error table header

fitbenchmarking/results_processing/energy_usage_table.py, fitbenchmarking/templates/table_descriptions.rst
Fixes #1386 
1. Check modified table description
2.
3.
=> Removed suggestions to install Intel Power Gadget

.pre-commit-config.yaml, fitbenchmarking/parsing/tests/test_parsers.py
Fixes the failing ruff [workflow](https://github.com/fitbenchmarking/fitbenchmarking/actions/runs/11972078944/job/33378218228) on the other PRs.
1. All the tests should pass
#1390
=> Made code compatible with ruff 0.8.0

pyproject.toml
=> Fixed authors typo in pyproject.toml

.github/workflows/install.yml
Fixes #1325 
I removed nlopt because it not building on Mac-os with python 3.13. It is installed in the integration test using conda. I did not want to over complicate this workflow so I have removed it from here.
1. The workflow should pass. Can be verified [here](https://github.com/fitbenchmarking/fitbenchmarking/actions/runs/12033609581/job/33548184334?pr=1395).
=> Updated install.yml to test install on python 3.13.x

README.md
Updates the Zenodo link.
1. The link should be directing to the latest release.
=> Updated Zenodo link in README.md

docs/source/conf.py, docs/source/contributors/guidelines.rst, docs/source/contributors/install_instructions.rst, docs/source/contributors/workflow.rst, docs/source/extending/adding_data.rst, docs/source/extending/fitting_results.rst, docs/source/extending/index.rst, docs/source/users/BenchmarkProblems.rst, docs/source/users/algorithms/deriv_free.rst, docs/source/users/algorithms/line_search.rst, docs/source/users/algorithms/trust_region.rst, docs/source/users/install_instructions/externals.rst, docs/source/users/options/minimizer_option.rst, docs/source/users/output/fitting_report.rst, docs/source/users/problem_definition_files/horace.rst, docs/source/users/running.rst, docs/source/users/tutorials.rst, fitbenchmarking/cli/checkpoint_handler.py, fitbenchmarking/cli/main.py, fitbenchmarking/controllers/base_controller.py, fitbenchmarking/controllers/ralfit_controller.py, fitbenchmarking/core/results_output.py, fitbenchmarking/cost_func/base_cost_func.py, fitbenchmarking/parsing/fitting_problem.py, fitbenchmarking/results_processing/tables.py, fitbenchmarking/utils/options.py
Fixes #1226 
1. `cd docs`
2. `make clean`
3. `make html`
4. Verify that docs build without any warnings
5. Verify that everything works well on the docs.
=> Fixed the warnings on docs build

Container/Containerfile
Required to test #1040 
1.
2.
3.
=> Added sscanss to test container

fitbenchmarking/controllers/gsl_controller.py, fitbenchmarking/core/results_output.py, fitbenchmarking/results_processing/performance_profiler.py, fitbenchmarking/results_processing/tests/test_plots.py, pyproject.toml
Added the [pandas-vet](https://docs.astral.sh/ruff/rules/#pandas-vet-pd) ruleset to ruff checks. It complained about using **df** as a variable name in the repo regardless of whether it was used for dataframes or not. So, these variable names are updated. It also recommends not using `inplace=True` because of inconsistent behaviour and no real performance benefit.
1. The precommit hook and github actions tests should pass.
=> Added the pandas-vet ruleset to ruff checks

fitbenchmarking/core/fitting_benchmarking.py, fitbenchmarking/core/tests/test_fitting_benchmarking.py
Reverted [name mangling](https://docs.python.org/3/tutorial/classes.html#private-variables) in the Fit class. This class will not have subclasses. So, the single underscore to identify private methods/variables should be a more maintainable way to indicate private attributes. 
1. All the tests should pass.
=> Refactored the Fit class to use single underscore for private method/variables instead of name mangling

docs/source/users/running.rst, fitbenchmarking/results_processing/fitting_report.py, fitbenchmarking/results_processing/plots.py, fitbenchmarking/results_processing/tests/test_fitting_report.py, fitbenchmarking/templates/fitting_report_template.html
Fixes #1451
Updated the fitting report to consolidate the tables for Problem Outline and Fitting Results.
Also consolidated the plots to show traces on that same axis.
**Note -** The changes also update the problem summary page. I might look into updating that page by doing something similar in another PR.
1. run `fitbenchmarking -s scipy_ls` verify everything looks okay.
2. run `fitbenchmarking --dont_make_plots` and verify there are no exceptions and the warning is displayed as follows.   
3. run `fitbenchmarking -p examples/benchmark_problems/SpinW_powder_data -s scipy_ls` and verify that the **SpinW** plots are consolidated.
=> Updated the fitting report template to consolidate the graphs and tables

.github/workflows/install.yml, .github/workflows/integration.yml, .github/workflows/main.yml
Fixes the failing tests. They broke because a new release of [setuptools](https://pypi.org/project/setuptools/#history) introducing a [bug](https://github.com/pypa/setuptools/issues/4910). I have temporary fixed them by introducing a constraint as suggested in the comments of the issue. The changes can be reverted when the issue is closed and new version of **setuptools** is released.
1. Verify the main tests [pass](https://github.com/fitbenchmarking/fitbenchmarking/actions/runs/14043147171)
2. Verify the integration tests [pass](https://github.com/fitbenchmarking/fitbenchmarking/actions/runs/14043147164) 
3. Verify the install tests [pass](https://github.com/fitbenchmarking/fitbenchmarking/actions/runs/14043147169)
=> Fixed the failing main, integration and install tests

.github/workflows/install.yml, .github/workflows/integration.yml, .github/workflows/main.yml
Fixes #1466
Merging this PR will fix the docs build badge. The constraint are also not required because `setuptools` quickly released a new version [78.0.2](https://github.com/pypa/setuptools/releases/tag/v78.0.2) after a lot of people raised issues. 
1. Verify the main tests [pass](https://github.com/fitbenchmarking/fitbenchmarking/actions/runs/14045313596)
2. Verify the integration tests [pass](https://github.com/fitbenchmarking/fitbenchmarking/actions/runs/14045313634) 
3. Verify the install tests [pass](https://github.com/fitbenchmarking/fitbenchmarking/actions/runs/14045313613)
=> Revert the updates to the main, integration and install tests

fitbenchmarking/results_processing/plots.py
Fixes #1473 
I've updated the legend style so that the legend appears at the bottom of plots. I've done this for both fitting report and summary page, as I think it's good for consistency and to have nicer bigger plots in both cases.
1. Run Fitbenchmarking with minimizers having long names
2. Check plots and legends in problem summary page and fitting reports
3.
4.
=> Fix legend at the bottom of plots
